---
genPolicy: "Create"
openAPISpec: "http://13.56.210.25/v2/api-docs"
generators:
- type: "empty_value"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  severity: null
  database: null
  inactive: false
  matches: []
- type: "sql_injection_timebound"
  assertions:
  - "@ResponseTime > 7000"
  - "@ResponseTime < 10000"
  - "@StatusCode != 404"
  severity: null
  database:
    name: "MySQL"
    version: "5.7"
  inactive: true
  matches: []
- type: "XSS_Injection"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  severity: null
  database: null
  inactive: true
  matches: []
- type: "log_Forging"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  severity: null
  database: null
  inactive: true
  matches: []
- type: "no_params"
  assertions:
  - "@StatusCode == 200"
  severity: null
  database: null
  inactive: true
  matches: []
- type: "sla"
  assertions:
  - "@StatusCode == 200"
  - "@StatusCode != 404"
  severity: null
  database: null
  inactive: true
  matches:
  - name: null
    value: "2000"
    methods: "Get"
    denyRoles: null
    pathPatterns: "/**"
    resourceSamples: null
    queryParams: null
    bodyProperties: null
- type: "anonymous_invalid"
  assertions:
  - "@StatusCode != 200"
  severity: null
  database: null
  inactive: true
  matches: []
- type: "auth_invalid"
  assertions:
  - "@StatusCode != 200"
  severity: null
  database: null
  inactive: true
  matches: []
- type: "rbac"
  assertions:
  - "@StatusCode == 403"
  severity: null
  database: null
  inactive: true
  matches:
  - name: "Admin access"
    value: null
    methods: "Post, Put, Delete"
    denyRoles: "Writer, Reader"
    pathPatterns: "/api/v1/orgs/**, /api/v1/accounts/**"
    resourceSamples: null
    queryParams: null
    bodyProperties: null
  - name: "Writer access"
    value: null
    methods: "Post, Put, Delete"
    denyRoles: "Reader"
    pathPatterns: "/api/v1/projects/**, /api/v1/regions/**"
    resourceSamples: null
    queryParams: null
    bodyProperties: null
  - name: "Collaborator access"
    value: null
    methods: "Post, Delete"
    denyRoles: "Collaborator"
    pathPatterns: "/api/v1/projects/**"
    resourceSamples: null
    queryParams: null
    bodyProperties: null
  - name: "Reader access"
    value: null
    methods: "Get, Post, Put, Delete"
    denyRoles: "Other"
    pathPatterns: "/api/v1/**"
    resourceSamples: null
    queryParams: null
    bodyProperties: null
- type: "DDOS"
  assertions:
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  severity: null
  database: null
  inactive: true
  matches:
  - name: "pageSize, page_size, maxResults, max_results"
    value: null
    methods: null
    denyRoles: null
    pathPatterns: null
    resourceSamples: null
    queryParams: null
    bodyProperties: null
- type: "invalid_datatype"
  assertions:
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  severity: null
  database: null
  inactive: true
  matches: []
- type: "special_chars "
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  severity: null
  database: null
  inactive: true
  matches: []
- type: "null_value"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  severity: null
  database: null
  inactive: true
  matches: []
- type: "negative_number"
  assertions:
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  severity: null
  database: null
  inactive: true
  matches: []
- type: "create"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  severity: null
  database: null
  inactive: true
  matches: []
