---
parent: "api_v1_projects_projectid_autocodeconfig"
name: "ApiV1ProjectsProjectidAutocodeconfigPostAuthInvalid"
description: null
type: "SUITE"
endpoint: "/api/v1/projects/{{@Random}}/autocodeconfig"
method: "POST"
auth: "INVALID_AUTH"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions:
- "@StatusCode != 200"
tags:
- "V1"
authors:
- "FX Bot"
category: "UnSecured"
severity: "Critical"
inactive: false
policies: null
