---

authors:
  - Intesar Shannan Mohammed

endpoint: /system-settings?page=-1&pageSize=10

method: GET

assertions:
  - "@StatusCode == 200"
  - "@Response.errors == true"

severity: Minor
category: Negative

tags:
  - V2
